services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    restart: always
    depends_on:
      - 'php-fpm'
    volumes:
      - './:/app'
      - './.docker/nginx:/etc/nginx/conf.d'
      - './.docker/log/nginx:/var/log/nginx'
  php-fpm:
    user: '1000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: "serverName=DockerBase"
    build:
      context: './.docker/php'
      dockerfile: './Dockerfile'
      args:
        APP_ENV: '${APP_ENV}'
    depends_on:
      - 'mysql'
      - 'memcached'
    volumes:
      - './:/app'
      - './.docker/php/conf.d/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini'
      #- './.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
  memcached:
    image: 'memcached:latest'
    ports:
      - '11211:11211'
  mysql:
    image: 'mysql:latest'
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './.docker/mysql/my.cnf:/etc/mysql/my.cnf'
      - 'mysqldata:/var/lib/mysql'
  supervisor:
      build:
          context: './.docker/supervisor'
          dockerfile: 'Dockerfile'
      container_name: 'supervisor'
      volumes:
          - './:/app'
volumes:
  mysqldata:
